lib: fwts_acpi_tables: fix the build fail on armhf
BugLink: https://bugs.launchpad.net/fwts/+bug/2059390

Currently, the update glib to libglib2.0-0t64 on armhf,
causes pointer-to-int-cast error, it seems build failed
with _FILE_OFFSET_BITS=64 on 32-bit.

fwts_acpi_tables.c:173:30: error: cast from pointer to integer of different size [-Werror=pointer-to-int-cast]
  173 |         if ((mem = fwts_mmap((off_t)addr, sizeof(fwts_acpi_table_rsdp))) == FWTS_MAP_FAILED)

fwts_acpi_tables.c:486:53: error: cast from pointer to integer of different size [-Werror=pointer-to-int-cast]
  486 |         fwts_acpi_add_table("RSDP", rsdp, (uint64_t)(off_t)rsdp_addr, rsdp_len, FWTS_ACPI_TABLE_FROM_FIRMWARE);

change the off_t to long int to fix this, let's see if any
update for this.

Signed-off-by: Ivan Hu <ivan.hu@canonical.com>