lib: fwts_acpi_tables: Fix compiler warning reported by Clang
When compiling fwts with Clang, the compiler complains:

 fwts_acpi_tables.c:1667:15: error: passing an object that undergoes default
  argument promotion to 'va_start' has undefined
       behavior [-Werror,-Wvarargs]
  1667 |         va_start(ap, num_type);
       |                      ^
 fwts_acpi_tables.c:1653:16: note: parameter of type 'const uint8_t' (aka
  'const unsigned char') is declared here
  1653 |         const uint8_t num_type,
       |                       ^

To fix the problem, let's swap the arguments of the function, so that
the last argument before the variadic list is a pointer instead of
a "uint8_t".

Signed-off-by: Thomas Huth <thuth@redhat.com>
Acked-by: Ivan Hu <ivan.hu@canonical.com>