uefi: uefirtauthvar: don't logically or a constant operand.
Cast constant operands to bool type so that the logical or does not
result in a clang warning.

Fixes clang build warning:

uefi/uefirtauthvar/uefirtauthvar.c:148:65: error: use of logical '||' with
constant operand [-Werror,-Wconstant-logical-operand]

Signed-off-by: Colin Ian King <colin.king@canonical.com>
Acked-by: Alex Hung <alex.hung@canonical.com>
Acked-by: Ivan Hu <ivan.hu@canonical.com>