acpica: rename vsnprintf and sprintf in utprint.c to avoid name clash conflicts
This temporary hack fixes build issues on s390x builds:

source/components/utilities/utprint.c:505:1: error: conflicting types for ‘vsnprintf’
 vsnprintf (
 ^
In file included from /usr/include/features.h:367:0,
                 from /usr/include/unistd.h:25,
                 from ./source/include/platform/aclinux.h:253,
                 from ./source/include/platform/acenv.h:257,
                 from ./source/include/acpi.h:128,
                 from source/components/utilities/utprint.c:116:
/usr/include/s390x-linux-gnu/bits/stdio2.h:74:1: note: previous definition of ‘vsnprintf’ was here
 __NTH (vsnprintf (char *__restrict __s, size_t __n,
 ^
source/components/utilities/utprint.c:801:1: error: conflicting types for ‘snprintf’
 snprintf (
 ^
In file included from /usr/include/features.h:367:0,
                 from /usr/include/unistd.h:25,
                 from ./source/include/platform/aclinux.h:253,
                 from ./source/include/platform/acenv.h:257,
                 from ./source/include/acpi.h:128,
                 from source/components/utilities/utprint.c:116:
/usr/include/s390x-linux-gnu/bits/stdio2.h:61:1: note: previous definition of ‘snprintf’ was here
 __NTH (snprintf (char *__restrict __s, size_t __n,

Signed-off-by: Colin Ian King <colin.king@canonical.com>
Acked-by: Ivan Hu <ivan.hu@canonical.com>
Acked-by: Alex Hung <alex.hung@canonical.com>