Fix null_gass initializer for older versions of gcc (LP: #1549429)
const fwts_acpi_gas null_gas = { 0 } causes a build failure with
older compilers, such as gcc 4.6 (on Trusty):

acpi/fadt/fadt.c: In function 'acpi_table_check_fadt_reduced_hardware':
acpi/fadt/fadt.c:447:2: error: missing initializer
  [-Werror=missing-field-initializers]
acpi/fadt/fadt.c:447:2: error: (near initialization for
  'null_gas.register_bit_width') [-Werror=missing-field-initializers]

make null_gas a static const - this will then be initialized as all
zeros just once at run time and it is compatible with older versions
of gcc too. Note this is a read-only struct, so this is fine to init
like this

Signed-off-by: Colin Ian King <colin.king@canonical.com>
Acked-by: Ivan Hu <ivan.hu@canonical.com>
Acked-by: Alex Hung <alex.hung@canonical.com>