acpica: fix linker issues when building with ACPI disabled
Some toolchains hit linker issues with missing symbols when
building with ACPI disabled.  Work around this by declaring
these symbols even though they are never referenced.

Works around PPC REHL 7.6 build issue:

/root/fwts/src/acpica/.libs/libfwtsacpica.so: undefined reference to
`AcpiGbl_InitEntries'
/root/fwts/src/acpica/.libs/libfwtsacpica.so: undefined reference to
`AcpiGbl_InitFileLineCount'

Fixes: 24f2f2bfbb8f ("ACPICA: Update to version 20180810")
Signed-off-by: Colin Ian King <colin.king@canonical.com>
Acked-by: Alex Hung <alex.hung@canonical.com>
Acked-by: Ivan Hu <ivan.hu@canonical.com>