lib: fwts_acpi_object_eval: fix build error on i386
the commit 87c45ec17740a37b13182453174ae80e55503900
fwts_acpi_object_eval: add a function to check buffer size

causes build error on i386
fwts_acpi_object_eval.c:590:4: error: format ‘%llu’ expects argument of type ‘long long unsigned int’, but argument 8 has type ‘size_t {aka unsigned int}’ [-Werror=format=]
    "%s should return a buffer of %" PRIu64 " bytes, "
    ^
../../../src/lib/include/fwts_framework.h:236:76: note: in definition of macro ‘fwts_failed’

fix the format.

Signed-off-by: Ivan Hu <ivan.hu@canonical.com>
Acked-by: Colin Ian King <colin.king@canonical.com>