cpu: virt: put extern virt helper func declarations in virt.h
Building with -Werror=missing-declarations picked up the following:

cpu/virt/virt_svm.c:67:6: error: no previous declaration
 for ‘virt_check_svm’ [-Werror=missing-declarations]
 void virt_check_svm(fwts_framework *fw)
      ^

So put the virt_check_* helper function declarations in virt.h
and include these in virt_*.c

Signed-off-by: Colin Ian King <colin.king@canonical.com>
Acked-by: Alex Hung <alex.hung@canonical.com>
Acked-by: Ivan Hu <ivan.hu@canonical.com>