lib: fwts_cmos: fix build error with non-Intel architectures
The dummy no-op CMOS fwts_cmos_read() for non-Intel builds
is causing build failures because of the -Wextra flag:

fwts_cmos.c: In function 'fwts_cmos_read':
fwts_cmos.c:53:34: error: unused parameter 'offset' [-Werror=unused-parameter]
fwts_cmos.c:53:51: error: unused parameter 'value' [-Werror=unused-parameter]

This fixes this and makes the no-op function return a known garbage
value.

Signed-off-by: Colin Ian King <colin.king@canonical.com>
Acked-by: Keng-Yu Lin <kengyu@canonical.com>
Acked-by: Ivan Hu <ivan.hu@canonical.com>