lib: fwts_uefi: fix build error when using gcc 4.6.3
With older versions of gcc we get a build failure:

fwts_uefi.c: In function 'fwts_uefi_print_status_info':
fwts_uefi.c:469:2: error: expected ')' before 'PRIx64'
fwts_uefi.c:469:2: error: spurious trailing '%' in format [-Werror=format]

..because some required headers were left out.

Signed-off-by: Colin Ian King <colin.king@canonical.com>
Acked-by: Keng-Yu Lin <kengyu@canonical.com>
Acked-by: Ivan Hu <ivan.hu@canonical.com>