acpi: spcr: remove unnecessary include files and fix ARM build issue
Fix build error, <sys/io.h> is not needed and causes build error on
ARM64:

acpi/spcr/spcr.c:27:20: fatal error: sys/io.h: No such file or directory
 #include <sys/io.h>

..and remove two more sys include files that are not required too.

Signed-off-by: Colin Ian King <colin.king@canonical.com>
Acked-by: Alex Hung <alex.hung@canonical.com>
Acked-by: Ivan Hu<ivan.hu@canonical.com>