wmi.c: fix build error when using gcc 4.6.3
With the precise of gcc 4.6.3 version we get the build error:

acpi/wmi/wmi.c:256:2: error: expected ‘)’ before ‘PRIx8’
acpi/wmi/wmi.c:256:2: error: conversion lacks type at end of format [-Werror=format]
acpi/wmi/wmi.c:260:2: error: expected ‘)’ before ‘PRIx8’
acpi/wmi/wmi.c:260:2: error: conversion lacks type at end of format [-Werror=format]
acpi/wmi/wmi.c: In function ‘wmi_parse_wdg_data’:
acpi/wmi/wmi.c:314:4: error: expected ‘)’ before ‘PRIx8’
acpi/wmi/wmi.c:314:4: error: conversion lacks type at end of format [-Werror=format]
acpi/wmi/wmi.c:316:4: error: expected ‘)’ before ‘PRIx8’
acpi/wmi/wmi.c:316:4: error: conversion lacks type at end of format [-Werror=format]
acpi/wmi/wmi.c:318:4: error: expected ‘)’ before ‘PRIx8’
acpi/wmi/wmi.c:318:4: error: conversion lacks type at end of format [-Werror=format]
acpi/wmi/wmi.c:320:4: error: expected ‘)’ before ‘PRIx8’
acpi/wmi/wmi.c:320:4: error: conversion lacks type at end of format [-Werror=format]

because some required headers were left out.

Signed-off-by: Ivan Hu <ivan.hu@canonical.com>
Acked-by: Keng-Yu Lin <kengyu@canonical.com>
Acked-by: Alex Hung <alex.hung@canonical.com>