lib: fwts_hwinfo.c: Fix strict aliasing build failure on Lucid (LP: #1251587)
With gcc gcc version 4.4.3 (Ubuntu 4.4.3-4ubuntu5.1) we are getting strict
aliasing warnings causing a build failure:

fwts_hwinfo.c: In function 'fwts_hwinfo_get':
fwts_hwinfo.c:418: error: dereferencing pointer '({anonymous})' does break strict-aliasing rules
fwts_hwinfo.c:418: note: initialized from here
make[5]: *** [fwts_hwinfo.lo] Error 1

This patch works around this issue.  Fromw what I understand, gcc 4.4.x was
rather (too?) strict on this kind of warning.

Signed-off-by: Colin Ian King <colin.king@canonical.com>
Acked-by: Alex Hung <alex.hung@canonical.com>
Acked-by: Ivan Hu <ivan.hu@canonical.com>