uefi: esrt: fix build failure due to lack of header file
-Wformat-security -c -o uefi/esrt/fwts-esrt.o `test -f
'uefi/esrt/esrt.c' || echo './'`uefi/esrt/esrt.c
uefi/esrt/esrt.c: In function ‘check_entries’:
uefi/esrt/esrt.c:105:6: error: expected ‘)’ before ‘PRIu32’
uefi/esrt/esrt.c:105:6: error: format ‘%s’ expects a matching ‘char *’
argument [-Werror=format]
uefi/esrt/esrt.c:105:6: error: spurious trailing ‘%’ in format
[-Werror=format]
uefi/esrt/esrt.c:137:6: error: expected ‘)’ before ‘PRIu32’
uefi/esrt/esrt.c:137:6: error: spurious trailing ‘%’ in format
[-Werror=format]
uefi/esrt/esrt.c:171:6: error: expected ‘)’ before ‘PRIu32’
uefi/esrt/esrt.c:171:6: error: format ‘%s’ expects a matching ‘char *’
argument [-Werror=format]
uefi/esrt/esrt.c:171:6: error: spurious trailing ‘%’ in format
[-Werror=format]
uefi/esrt/esrt.c: In function ‘esrt_test1’:
uefi/esrt/esrt.c:237:4: error: expected ‘)’ before ‘PRIu64’
uefi/esrt/esrt.c:237:4: error: spurious trailing ‘%’ in format
[-Werror=format]
cc1: all warnings being treated as errors

Signed-off-by: Ivan Hu <ivan.hu@canonical.com>
Acked-by: Alex Hung <alex.hung@canonical.com>