uefi: uefivariable: fix build error on older compilers
Curiously, we are getting the following error on older versions
of GCC:

cc1: warnings being treated as errors
uefi/uefirtvariable/uefirtvariable.c: In function 'getnextvariable_test2':
uefi/uefirtvariable/uefirtvariable.c:352:5: error: array subscript is above array bounds

..and it only happens on 32 bit builds.

Looking at the compiled object code, it seems that:

c = variablename[(len / sizeof(c)) - 1];

produces an add of 0xffffffff todo the subtraction of -1
which triggers the array subscript array bounds warning, where as:

uint64_t i = (len / sizeof(c)) - 1;

c = variablename[i];

produces a subtraction of 1 and everthing is fine.

This patch is a workaround.  I've hand checked the result, and it
produces the code we require, so I think the original code was OK
but GCC was being overly zealous.

Signed-off-by: Colin Ian King <colin.king@canonical.com>
Acked-by: Ivan Hu <ivan.hu@canonical.com>
Acked-by: Alex Hung <alex.hung@canonical.com>