lib: fix build error on non-Intel platforms
Fix for build error:
  fwts_dump.c: In function 'fwts_dump_info':
  fwts_dump.c:259:7: error: unused variable 'root_priv' [-Werror=unused-variable]
  cc1: all warnings being treated as errors

Fixes: 6e9c327a42017de ("lib: Allow reading ACPI dump file by non-root user")
Signed-off-by: Colin Ian King <colin.king@canonical.com>
Acked-by: Ivan Hu<ivan.hu@canonical.com>
Acked-by: Alex Hung <alex.hung@canonical.com>