efi_runtime: ensure it always builds for kernels > 3.0.0 (LP: #1198168)
On an old 3.0 kernel we get:

make -C /lib/modules/`uname -r`/build M=`pwd` modules
make[1]: Entering directory `/usr/src/linux-headers-3.0.0-12-generic'
  CC [M] /home/king/fwts/efi_runtime/efi_runtime.o
/home/king/fwts/efi_runtime/efi_runtime.c: In function ‘efi_runtime_ioctl’:
/home/king/fwts/efi_runtime/efi_runtime.c:285:15: error: ‘struct efi’ has no member named ‘query_variable_info’
/home/king/fwts/efi_runtime/efi_runtime.c:315:15: error: ‘struct efi’ has no member named ‘query_capsule_caps’
/home/king/fwts/efi_runtime/efi_runtime.c:316:6: error: ‘efi_capsule_header_t’ undeclared (first use in this function)
/home/king/fwts/efi_runtime/efi_runtime.c:316:6: note: each undeclared identifier is reported only once for each function it appears in
/home/king/fwts/efi_runtime/efi_runtime.c:316:29: error: expected expression before ‘)’ token
make[2]: *** [/home/king/fwts/efi_runtime/efi_runtime.o] Error 1
make[1]: *** [_module_/home/king/fwts/efi_runtime] Error 2
make[1]: Leaving directory `/usr/src/linux-headers-3.0.0-12-generic'
make: *** [all] Error 2

..since query_variable_info and query_capsule_caps are really supported until
3.1 lets make these conditional on the kernel version.

Signed-off-by: Colin Ian King <colin.king@canonical.com>
Acked-by: Alex Hung <alex.hung@canonical.com>
Acked-by: Ivan Hu <ivan.hu@canonical.com>