acpica: fix the build error after patch the update to ACPICA version 20130418
Got the build error after applying the [PATCH] acpica: update to ACPICA version 20130418.
../src/acpica /home/ivanhu/work/temp/temp/fwts/src/acpica/.libs/libfwtsacpica.so -Wl,-rpath -Wl,/usr/lib/fwts
/home/ivanhu/work/temp/temp/fwts/src/acpica/.libs/libfwtsacpica.so: undefined reference to `clock_gettime'
collect2: ld returned 1 exit status
make[3]: *** [fwts] Error 1
make[3]: Leaving directory `/home/work/temp/temp/fwts/src'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory `/home/work/temp/temp/fwts/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/work/temp/temp/fwts'
make: *** [all] Error 2

Signed-off-by: Ivan Hu <ivan.hu@canonical.com>
Acked-by: Colin Ian King <colin.king@canonical.com>
Acked-by: Alex Hung <alex.hung@canonical.com>