lib: framework: pack fwts_framework_flags to ensure it is a 32 bit int
recent commit c4091edad369beb12b451a0ab5f233fcda05a5f3
("Add in the notion of ACPI compliance tests.") make the fwts_framework_flags
enum into a 64 bit integer which now breaks 32 bit builds:

fwts_framework.c: In function 'fwts_framework_test_add':
fwts_framework.c:155:4: error: format '%lx' expects argument of type
   'long unsigned int', but argument 4 has type 'long long unsigned int'
   [-Werror=format]

Since we have a bunch of spare bits in this enum, re-orginaise the bits to
pack this into a 32 bit enum.  Once we've used all these bits up we should
consider making the enum into a 64 bit integer, but for now, try to save
a few bytes by keeping this a 32 bit integer.

Signed-off-by: Colin Ian King <colin.king@canonical.com>
Acked-by: Alex Hung <alex.hung@canonical.com>
Acked-by: Ivan Hu <ivan.hu@canonical.com>