acpi: xsdt: fix build error on 32 bit systems
Use PRIu64 rather than lx to print the address. Also minor change
to else formatting.

Fixes build error:
acpi/xsdt/xsdt.c: In function ‘xsdt_test1’:
acpi/xsdt/xsdt.c:84:4: error: format ‘%lx’ expects argument of type
‘long unsigned int’, but argument 7 has type ‘uint64_t’ [-Werror=format=]
    fwts_passed(fw, "XSDT is present, pointed at by XsdrAddress=0x%lx"
    ^

Fixes: fcc5f1e9fbc7 ("acpi: xsdt: add SBBR compliance tests)
Signed-off-by: Colin Ian King <colin.king@canonical.com>
Acked-by: Alex Hung <alex.hung@canonical.com>
Acked-by: Ivan Hu <ivan.hu@canonical.com>