acpi: acpidump: fix 32 bit build error
Commit "acpi: acpidump: check for short length headers (LP: #1375300)"
introduced a build error because of the wrong format specifier for
the table length.

acpi/acpidump/acpidump.c: In function 'acpidump_slit':
acpi/acpidump/acpidump.c:1059:3: error: format '%llu' expects argument of
  type 'long long unsigned int', but argument 9 has type 'size_t' [-Werror=format]
cc1: all warnings being treated as errors

This one-liner fix addresses that bug.

Signed-off-by: Colin Ian King <colin.king@canonical.com>
Acked-by: Keng-Yu Lin <kengyu@canonical.com>