autobrightness: fix calloc argument order for GCC 15 compatibility
BugLink: https://bugs.launchpad.net/fwts/+bug/2110601

Fix a build failure with GCC 15 caused by incorrect argument order in calloc().
The first argument should be the number of elements, and the second the size of
each element.
With the wrong arguments, got the GCC 15 build fail below,
acpi/brightness/autobrightness.c: In function ‘auto_brightness_test2’:
acpi/brightness/autobrightness.c:134:49: error: ‘calloc’ sizes specified with ‘sizeof’ in the earlier argument and not in the later argument [-Werror=calloc-transposed-args]
  134 | brightness_fail = calloc(sizeof(bool), max_brightness + 1);
      | ^~~~
acpi/brightness/autobrightness.c:134:49: note: earlier argument should specify number of elements, later size of each element
cc1: all warnings being treated as errors

Signed-off-by: Ivan Hu <ivan.hu@canonical.com>